export const AuthConstant = {
    INIT_URL: 'AUTH_INIT_URL',

    SIGN_IN: 'AUTH_SIGN_IN',
    SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',

    SIGN_OUT: 'AUTH_SIGN_OUT',
    SIGN_OUT_SUCCESS: 'AUTH_SIGN_OUT_SUCCESS',

    GET_TOKEN_SILENTLY: 'AUTH_GET_TOKEN_SILENTLY',
    GET_TOKEN_SILENTLY_SUCCESS: 'AUTH_GET_TOKEN_SILENTLY_SUCCESS',
};
