export const CalendarConstant = {
    GET_EVENTS: 'CALENDAR_GET_EVENTS',
    GET_EVENTS_SUCCESS: 'CALENDAR_GET_EVENTS_SUCCESS',

    CREATE_EVENT: 'CALENDAR_CREATE_EVENT',
    CREATE_EVENT_SUCCESS: 'CALENDAR_CREATE_EVENT_SUCCESS',

    UPDATE_EVENT: 'CALENDAR_UPDATE_EVENT',
    UPDATE_EVENT_SUCCESS: 'CALENDAR_UPDATE_EVENT_SUCCESS',

    DELETE_EVENT: 'CALENDAR_DELETE_EVENT',
    DELETE_EVENT_SUCCESS: 'CALENDAR_DELETE_EVENT_SUCCESS',

    URL_CALENDAR: '/app/calendar/',
};
